//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApp.Core.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public Check()
        {
            this.CheckTransactions = new HashSet<CheckTransaction>();
        }
    
        public int Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public decimal Amount { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<CheckTransaction> CheckTransactions { get; set; }
        public virtual Account PayeeAccount { get; set; }
    }
}
