//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApp.Core.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseItem
    {
        public int Id { get; set; }
        public int ExpenseId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string Description { get; set; }
        public string ORNumber { get; set; }
        public int ProjectId { get; set; }
        public decimal Amount { get; set; }
        public ExpenseCategory Category { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual Account CompanyAccount { get; set; }
        public virtual Project Project { get; set; }
    }
}
