//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApp.Core.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public Expense()
        {
            this.ExpenseItems = new HashSet<ExpenseItem>();
        }
    
        public int Id { get; set; }
    
        public virtual Voucher Voucher { get; set; }
        public virtual ICollection<ExpenseItem> ExpenseItems { get; set; }
    }
}
