//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApp.Core.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public VoucherType Type { get; set; }
    
        public virtual CheckTransaction CheckTransaction { get; set; }
        public virtual Account PayeeAccount { get; set; }
        public virtual Expense Expense { get; set; }
    }
}
