//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApp.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Check
    {
        public Check()
        {
            this.CheckTransactions = new List<CheckTransaction>();
        }
    
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string Notes { get; set; }
        public int TransactionAccountId { get; set; }

        public virtual List<CheckTransaction> CheckTransactions { get; set; }
        //public virtual TransactionAccount TransactionAccount { get; set; }
        [NotMapped]
        public TransactionAccount TransactionAccount { get; set; }
    }
}
