//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApp.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Expenses = new List<Expense>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
    
        public  List<Expense> Expenses { get; set; }
    }
}
